### ISSUE TITLE
identifier scheme

### ISSUE THREAD

**Issue by ksonda** [internetofwater/CA-Gages#7]
NLDI integration (#5 ) requires persistent identifiers. Need to come up with CA-wide identifier scheme. Can use https://geoconnex.us as resolver

**Comment by vlzimmer** [comment]
ok?  the UC code does the gage gap analysis in R.  I'm actually not sure what I'm supposed to do with this?

**Comment by ksonda** [comment]
We already decided this. For example https://geoconnex.us/ca-gage-assessment/gages/ABJ now persistently identifies CDEC station ABJ

Closing
